# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='localizacion por defecto', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='descripcion por defecto'),
        ),
    ]
