# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170302_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='descripcion por defecto'),
        ),
    ]
